# Using 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Prepackaged CircleCI Python config orb
orbs:
  python: circleci/python@1.5.0

# Defining jobs
jobs:
  build-and-test: # This is the name of the job, feel free to change it to better match what you're trying to do!
    # Docker executor from CircleCI
    # Python version
    docker:
      - image: cimg/python:3.10.2
    # Checkout the code as the first step. This is a dedicated CircleCI step.
    # The python orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
    # Here we're making sure we use just use the system-wide pip. By default it uses the project root's requirements.txt.
    # Then run your tests!
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          # Here just using the command line way of running the test file
          command: python test_import_remover.py
          coverage run -m pytest
          coverage report
          coverage html
          
      - store_artifacts:
        path: htmlcov

# Invoke jobs via workflows
workflows:
  main: # Running job defined above
    jobs:
      - build-and-test
